### ISSUE TITLE
Better color customization experience, using unjs/theme-colors

### ISSUE THREAD

**Issue by oumarbarry** [benjamincanac/ui3#117]
### Description

Using [unjs/theme-colors](https://unjs.io/packages/theme-colors), could somehow maybe improve the color theming experience, for both.

<br>

Behind the scenes, for you the lib author

and/or

For us, lib users, it could enable enhancement like the ability to pass an arbitrary hex/rgb color code and get shades generated by [unjs/theme-colors](https://unjs.io/packages/theme-colors):

```ts
export default defineAppConfig({
  ui: {
    primary: '#BC560A',
    gray: 'cool'
  }
})
```

**Comment by benjamincanac** [comment]
The colors defined to `ui.primary` and `ui.gray` are aliases to Tailwind CSS colors, we can't define your tailwind config inside the `app.config.ts`. You should be able to use `unjs/theme-colors` in your `tailwind.config.ts` though.
