### ISSUE TITLE
[Docs] Invisible code expressions in light mode

### ISSUE THREAD

**Issue by romhml** [benjamincanac/ui3#148]
### Description

The syntax highlighting used in code snippets renders some expression in white, making them invisible when browsing the documentation in light mode.

See `/components/breadcrumb` for example:
<img width="734" alt="image" src="https://github.com/user-attachments/assets/c7a21fe1-df60-4719-ac77-2c9b30bda215">

**Comment by benjamincanac** [comment]
@romhml This is not really an issue, since Dark mode is not yet available in Tailwind CSS v4 I've disabled `@nuxtjs/color-mode` which means there are no `light` / `dark` class applied on `<html>` and Shiki depends on these classes.

This will be fixed by itself at some point 😊
