### ISSUE TITLE
[Drawer] Missing animation when closing programatically

### ISSUE THREAD

**Issue by benjamincanac** [benjamincanac/ui3#54]
https://github.com/radix-vue/vaul-vue/issues/33

**Comment by robin-dongbin** [comment]
I think we should build this by ourself, based on radix-ui dialog

**Comment by robin-dongbin** [comment]
I saw we have a `Slideover` component already, what is diffrent with `Drawer`?

**Comment by benjamincanac** [comment]
The `vaul-vue` repository is part of Radix Vue, I don't see why we wouldn't use the available primitives, it works well 😊

**Comment by robin-dongbin** [comment]
I don't think we need this, I think we should rename `Slideover` to `Drawer`

**Comment by Saeid-Za** [comment]
Better to be based on a unified ecosystem!
Although I tried to find a solution when I first encountered the issue, I'll try again.

**Comment by robin-dongbin** [comment]
Since I checked this component, it seems to be a parody IOS component built specifically for mobile, which is not the same as a component in a `Drawer` in most component libraries.

Instead, the `Silderover` component looks like a `Drawer` in most component libraries
