### ISSUE TITLE
License for UI PRO ( based in ui 3 )

### ISSUE THREAD

**Issue by ncodealex** [benjamincanac/ui3#62]
### Description

Hello, thank for the great product. I have a big pet project ahead of me that I would like to use UI PRO.  I get updates UI Pro v3  if now pay ?  

How long do you want to rewrite UI Pro to new UI 3 version ? 

Thank !

**Comment by benjamincanac** [comment]
We're working on Nuxt UI Pro `v2` (that will include Nuxt UI `v3`) in parallel. This will be a free update, you can read more about this in this issue: https://github.com/nuxt/ui-pro/issues/326.

**Comment by ncodealex** [comment]
Thanks for you reply!
