### ISSUE TITLE
Can't run anymore `pnpm install`

### ISSUE THREAD

**Issue by mauroerta** [benjamincanac/ui3#82]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     ^3.11.2
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@9.0.6
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Version

v3.0.0

### Reproduction

https://stackblitz.com/~/github.com/mauroerta/ui3

### Description

`pnpm install` does not work anymore, here is the error I'm getting:

```console
Scope: all 5 workspace projects
/Users/my-username/path/to/ui3/docs:
 ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND  Could not install from "/Users/my-username/path/to/ui-pro2" as it does not exist.

This error happened while installing a direct dependency of /Users/my-username/path/to/ui3/docs
```

It seems there is a reference to `ui-pro2` inside the `docs` package, in fact, if I remove `docs` from `pnpm-workspace.yaml` everything works: (or at least, I can run `pnpm install`)

```diff
packages:
  - "./"
  - "cli"
-  - "docs"
  - "playground"
  - "modules/*"
```

**Comment by benjamincanac** [comment]
Indeed I'm using this to develop `@nuxt/ui-pro` v2 is parallel as it's not published yet. You can remove `docs` from the `pnpm-workspace.yaml` while developing!
